import = [
    "~/.config/alacritty/themes/themes/github_light.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[cursor.style]
shape = "Block"
blinking = "Off"

[cursor]
vi_mode_style.shape = "Block"
